#!/usr/bin/env bash
# Regenerate the golden example/ tree: cookiecutter-django (pinned) + harness overlay.
#
# The output is deterministic. The overlay never resolves dependencies from the network,
# so this script only produces a diff when the pin, the overlay, or dev-requirements.txt
# actually changed. `uv.lock` is the one exception: it is regenerated from the pinned
# `==` requirements, and CI verifies it with `uv lock --check` instead of a byte diff.
set -euo pipefail

HARNESS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXAMPLE_DIR="${HARNESS_ROOT}/example"
STAGING="$(mktemp -d)"
trap 'rm -rf "${STAGING}"' EXIT

command -v uv >/dev/null || { echo "error: uv is required — https://docs.astral.sh/uv/" >&2; exit 1; }

REF="${COOKIECUTTER_DJANGO_REF:-$(uv run --project "${HARNESS_ROOT}" python -c \
  'from django_ai_harness.pins import cookiecutter_ref; print(cookiecutter_ref())')}"

echo "==> Generating golden example from cookiecutter-django @ ${REF}"
COOKIECUTTER_DJANGO_REF="${REF}" uv run --project "${HARNESS_ROOT}" django-ai-harness new \
  "${STAGING}/harness_example" "Harness Example" \
  --slug harness_example \
  --description "Golden example for django-ai-harness" \
  --author-name "django-ai-harness" \
  --email "maintainers@example.com" \
  --domain-name "example.com"

GENERATED="${STAGING}/harness_example"

# cookiecutter-django seeds a fresh random SECRET_KEY into local.py and test.py on every
# generation. That is correct for a real project and fatal for a golden fixture: the tree
# would differ on every run and the CI comparison could never pass. Normalise the two
# defaults to an obviously fake constant. The substitution fails loudly if upstream
# changes the shape of the assignment, which is exactly when we want to know.
echo "==> Normalising generated secrets"
python3 - "${GENERATED}" <<'PY'
import re
import sys
from pathlib import Path

PLACEHOLDER = "django-ai-harness-golden-example-secret-key-not-for-real-use-0001"
PATTERN = re.compile(
    r'(SECRET_KEY = env\(\s*\n\s*"DJANGO_SECRET_KEY",\s*\n\s*default=")[^"]+(")',
)

root = Path(sys.argv[1])
for relative in ("config/settings/local.py", "config/settings/test.py"):
    path = root / relative
    text = path.read_text(encoding="utf-8")
    normalised, count = PATTERN.subn(rf"\g<1>{PLACEHOLDER}\g<2>", text)
    if count != 1:
        sys.exit(f"error: could not normalise SECRET_KEY in {relative}")
    path.write_text(normalised, encoding="utf-8")
PY

echo "==> Locking dependencies"
(cd "${GENERATED}" && uv lock --quiet)

# Never carry local build artefacts into the committed tree.
rm -rf "${GENERATED}/.venv" "${GENERATED}/.git"

cat > "${GENERATED}/HARNESS_EXAMPLE.md" <<'EOF'
# Golden example

Generated by `scripts/refresh-example.sh` (cookiecutter-django at the pinned ref, plus
the django-ai-harness overlay). CI regenerates this tree on every pull request and fails
if the committed result differs, which is how upstream drift and accidental overlay
changes surface early.

Do not hand-edit. Change the overlay and regenerate:

```bash
./scripts/refresh-example.sh
```

## Environment files and secrets

Generated with `keep_local_envs_in_vcs=n`, so `.envs/` is **not** committed. Create local
env files from the cookiecutter-django documentation before running Compose. Never commit
real credentials.

The `SECRET_KEY` defaults in `config/settings/local.py` and `config/settings/test.py` are
replaced with a fixed placeholder during regeneration. cookiecutter-django seeds a fresh
random key on every run, which would make this tree differ on every regeneration and
defeat the CI comparison. Your own generated projects get a real random key.
EOF

echo "==> Replacing ${EXAMPLE_DIR}"
rm -rf "${EXAMPLE_DIR}"
mv "${GENERATED}" "${EXAMPLE_DIR}"

echo "example/ refreshed"
