#!/usr/bin/env bash
# Regenerate example/ from cookiecutter-django (pinned ref) + overlay.
set -euo pipefail

HARNESS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXAMPLE_DIR="${HARNESS_ROOT}/example"
TMP="$(mktemp -d)"
COOKIECUTTER_DJANGO_REF="${COOKIECUTTER_DJANGO_REF:-cdbe7265c79f43fd3e22c4527a97c8c7a5c72a5b}"
cleanup() { rm -rf "${TMP}"; }
trap cleanup EXIT

command -v cookiecutter >/dev/null || { echo "error: cookiecutter not found"; exit 1; }
command -v uv >/dev/null || { echo "error: uv not found"; exit 1; }

echo "==> Generating golden example @ ${COOKIECUTTER_DJANGO_REF}"
cookiecutter "gh:cookiecutter/cookiecutter-django" --checkout "${COOKIECUTTER_DJANGO_REF}" --no-input --output-dir "${TMP}" \
  project_name="Harness Example" \
  project_slug="harness_example" \
  description="Golden example for django-ai-harness" \
  author_name="django-ai-harness" \
  domain_name="example.com" \
  email="maintainers@example.com" \
  open_source_license="MIT" \
  username_type="email" \
  timezone="UTC" \
  windows="n" \
  editor="None" \
  use_docker="n" \
  cloud_provider="None" \
  mail_service="Other SMTP" \
  rest_api="DRF" \
  use_async="n" \
  frontend_pipeline="None" \
  use_celery="n" \
  mail_catcher="None" \
  use_sentry="n" \
  use_whitenoise="y" \
  use_heroku="n" \
  ci_tool="Github" \
  keep_local_envs_in_vcs="y" \
  debug="n"

GENERATED="${TMP}/harness_example"
python3 "${HARNESS_ROOT}/overlay/apply.py" "${GENERATED}" --harness-root "${HARNESS_ROOT}"

rm -rf "${GENERATED}/.venv" "${GENERATED}/.git" || true

echo "==> Replacing ${EXAMPLE_DIR}"
rm -rf "${EXAMPLE_DIR}"
mkdir -p "${HARNESS_ROOT}"
mv "${GENERATED}" "${EXAMPLE_DIR}"

cat > "${EXAMPLE_DIR}/HARNESS_EXAMPLE.md" <<'EOF'
# Golden example

This tree is generated by `scripts/refresh-example.sh` (cookiecutter-django + overlay).
Do not hand-edit except when fixing overlay output; prefer changing the overlay and regenerating.

## About `.envs/`

Files under `.envs/` are **cookiecutter-django placeholders** kept because
`keep_local_envs_in_vcs=y`. They are **not** production secrets. Never deploy this
example with those values; rotate credentials for any real environment.
EOF

echo "example/ refreshed"
